import type { Metadata } from "next";
import "./globals.css";
import { NavBar } from "@/components/NavBar/NavBar";
import AuthProvider from "@/providers/AuthProvider/AuthProvider";
import AnalysisProvider from "@/providers/AnalysisProvider/AnalysisProvider"; // 👈 ADICIONE

export const metadata: Metadata = {
  title: "EchoWeb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-white">
        <AuthProvider>
          <AnalysisProvider> 
            <NavBar />
            {children}
          </AnalysisProvider>
        </AuthProvider>
      </body>
    </html>
  );
}